//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtMae_Empleados
    {
        public int idrow { get; set; }
        public string EmpleadoCodigo { get; set; }
        public string EmpleadoNombres { get; set; }
        public string EmpleadoApellidos { get; set; }
        public string Cedula { get; set; }
        public string EmpresaCodigo { get; set; }
        public string PuntoVentaCodigo { get; set; }
        public int CargoId { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public Nullable<bool> IndDesayuno { get; set; }
        public Nullable<bool> IndAlmuerzo { get; set; }
        public Nullable<bool> IndComida { get; set; }
        public Nullable<bool> IndCena { get; set; }
        public Nullable<bool> IndLunch { get; set; }
        public Nullable<bool> IndLunchEspecial { get; set; }
        public Nullable<bool> IndManualCliente { get; set; }
        public Nullable<bool> IndRefrigerios { get; set; }
        public Nullable<int> CantidadPermitidas { get; set; }
        public Nullable<bool> AutorizacionPuntoVenta { get; set; }
        public Nullable<bool> MultiReservas { get; set; }
        public Nullable<bool> IndVivienda { get; set; }
        public Nullable<bool> IndViviendaBase { get; set; }
        public string ViviendaCodigo { get; set; }
        public string HabitacionCodigo { get; set; }
        public string CamaCodigo { get; set; }
        public string Nota { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Genero { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> FechaAdEd { get; set; }
        public string antcargo { get; set; }
        public Nullable<int> idcliente { get; set; }
        public string antpventa { get; set; }
        public Nullable<bool> IndVisitante { get; set; }
        public string Tarjeta { get; set; }
    }
}
